[package]
name = "p2p_node_handshake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: cleanup
anyhow = "1.0.72"
bytes = "1.4.0"
libp2p = { version = "0.52.1", features = ["full"] }
prost = "0.11.9"
snow = "0.9.2"

[build-dependencies]
prost-build = "0.11.9"
